---
- hosts: all
  gather_facts: False
  remote_user: ubuntu
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: Install Python 2
      raw:  apt-get update && apt-get install -y python

    - name: fancy way of doing authorised keys
      authorized_key: user=root
                      exclusive=no
                      key="{{ lookup('file','~/.ssh/id_rsa.pub') }}"

