---
- name: SYSTEM | Install basic database packages
  package: name={{ item }} state=present
  with_items: 
    - postgresql
    - postgresql-contrib
    - python-psycopg2

- name: POSTGRES | Create db
  become: true
  become_user: postgres
  postgresql_db:
    name: mattermost

- name: POSTGRES | Create db user
  become: yes
  become_user: postgres
  postgresql_user:
    db: mattermost
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: ALL

- name: POSTGRES | Create db priviledges
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ db_user }}"
    role_attr_flags: NOSUPERUSER,NOCREATEDB

- block: 
  - name: POSTGRES | setup hba
    template: src=pg_hba.conf dest={{ PG_HBA_CONF }}
    notify:
      - restart postgres
  - name: POSTGRES | listen on all IPs
    lineinfile:
      dest: "{{ PG_CONF }}"
      line: listen_addresses_'*'
    notify:
     - restart postgres
  when: hostvars[groups['webservers'][0]]['inventory_hostname'] != inventory_hostname

